### ISSUE TITLE
Plugin 0 specified in "base" provided an invalid property of "babiliOpts"

### ISSUE THREAD

**Issue by anthonator** [webpack-contrib/babili-webpack-plugin#52]
I'm receiving the following error when running `babili-webpack-plugin` with the following entry in my webpack config.

```js
plugins: [
  new BabiliWebpackPlugin({}, { comments: false })
]
```

I'm using version 3.3.0 of webpack.

```
errors: 
      [ ModuleBuildError: Module build failed: Error: Plugin 0 specified in "base" provided an invalid property of "babiliOpts"
            at Plugin.init (/usr/src/app/node_modules/babel-core/lib/transformation/plugin.js:131:13)
            at Function.normalisePlugin (/usr/src/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
            at /usr/src/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
            at Array.map (native)
            at Function.normalisePlugins (/usr/src/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
            at OptionManager.mergeOptions (/usr/src/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
            at OptionManager.init (/usr/src/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
            at File.initOptions (/usr/src/app/node_modules/babel-core/lib/transformation/file/index.js:212:65)
            at new File (/usr/src/app/node_modules/babel-core/lib/transformation/file/index.js:135:24)
            at Pipeline.transform (/usr/src/app/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
            at transpile (/usr/src/app/node_modules/babel-loader/lib/index.js:49:20)
            at Object.module.exports (/usr/src/app/node_modules/babel-loader/lib/index.js:174:20)
            at runLoaders (/usr/src/app/node_modules/webpack/lib/NormalModule.js:194:19)
            at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:364:11
            at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:230:18
            at runSyncOrAsync (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
            at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
            at Array.<anonymous> (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
            at Storage.finished (/usr/src/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
            at /usr/src/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
            at /usr/src/app/node_modules/graceful-fs/graceful-fs.js:78:16
            at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3) ],
```

**Comment by anthonator** [comment]
Nevermind. User error.

**Comment by mrslimslim** [comment]
Hello ,I came cross the error.What exactly is the User error?
